name: Clans2023
description: Simple clans plugin for PulseMC
version: '${project.version}'
main: br.com.pulse.clans.Main
depend: [BedWars2023]
softdepend: [PlaceholderAPI, LeafPlugins, LeafPunish]
commands:
  clan:
    aliases: [guild, cla]
    description: Clans
  cc:
    aliases: [clanchat]
    description: Chat clans